// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puqeuzuidvofsstoykee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1cWV1enVpZHZvZnNzdG95a2VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTE3MDQsImV4cCI6MjA2NDYyNzcwNH0.OEEQI3k4vC9S3k93Oun7Ro3ZoaQxvFbtmmsyAWFf24I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);